### ISSUE TITLE
Support `privileged_action`

### ISSUE THREAD

**Issue by luben** [CardinalBytes/daemonize-me#14]
Currently I use the `privileged_action` in `daemonize` to open some files in `/proc/self` before the process changes user/group so I can sample some stats about the running process. I have not found another approach that may work for this - if I open the files before `demonize.start` they will be referring not to the process I want to be monitored.

Is there possibility to add optional `privileged_action` method that takes a `FnOnce`? For reference: https://docs.rs/daemonize/latest/daemonize/struct.Daemonize.html#method.privileged_action

**Comment by xadaemon** [comment]
Hello @luben I think this is covered in the 2.0 upcoming major version by one of the hooks it adds, if you want to try it out, the full 2.0.0 release is very close and the api is stable by this point.

**Comment by luben** [comment]
Thanks, I was looking at the default branch so I missed it.

**Comment by luben** [comment]
I should have tried to migrate before v2.0 is released. I tried to port my code to use `demonize-me` and found few issues:
- the hooks accept `fn(i32, i32)`, i.e. they are defined as `fn hook(&self, fn(i32, i32)`. This is more restrictive than accepting a closure, i.e. `fn hook<F: Fn(i32,32)>(f: F)`
- at least the `child_post_fork` hook will be useful to get `Fn(i32, i32) -> Result<T, Error>` as a param and the result returned by the `start()` call. This is the case with the `privileged_action` in `daemonize`. With current implementation it would require some global mutable state that is less than ideal.

**Comment by xadaemon** [comment]
I guess I can add a `privileged_action_hook` or something named along those lines to keep consistency, and not have to go for a major 3 release so soon.

**Comment by luben** [comment]
That's the least invasive option. Another will be to change the existing hook:

- we can change `fn()` to `F: Fn()` as it's more general
- we can change `Fn()` to `T, Fn()->T` as it will be infered to `T=()`

Though I think there is a risk - not sure it it will be 100% compatible.

**Comment by xadaemon** [comment]
I will experiment with the ideas you gave in a branch named devel/2.1.0, or if you want to try the change yourself and contribute a pr it'd be much appreciated.

edit:
I have changed it in a way that's compatible with 2.0, and I think I will experiment with a 3.0 branch for more freedom to achieve a better API. @luben let me know if what's in devel/2.1.0 is what you had in mind at least sort of?

Regards

**Comment by xadaemon** [comment]
I will say though that I'm plenty willing to make an early 3.0 release if the API ergonomics improvement is significant
